#  Use Hugo setup : https://github.com/marketplace/actions/hugo-setup
name: Deploy
on:
  push:
    branches:
      - main # 只在main上push触发部署
    #   - add_hugo
    # paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
    #   - README.md
    #   - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - name: Checkout
        uses: actions/checkout@v2 # 第一步，下载代码仓库
        with:
          submodules: true # Fetch Hugo themes (true OR recursive) #!!!!重点
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Hugo setup # 第二步，安装Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "latest"
          extended: true # use a Hugo extended version.
        # with:
        #   hugo-version: '0.86.1'

      - name: Build Hugo # 编译Hugo
        run: hugo -D --minify
        # with:
        #   publish_dir: ./public
      #   Output will be in ./public/ directory by default
      # (-d/--destination flag to change it, or set publishdir in the config file).
      # Example:   hugo -D --minify

      #  Caitouyun
      - name: Caitou Deploy
        run: |
          curl -sf https://cli.caitouyun.com/install.sh | sh
          caitou deploy --git
        env:
          CAITOU_TOKEN: ${{ secrets.CAITOU_TOKEN }}
#  Original
#
# # # This is a basic workflow to help you get started with Actions
#
# # name: CI
#
# # # Controls when the workflow will run
# # on:
# #   # Triggers the workflow on push or pull request events but only for the "master" branch
# #   push:
# #     branches: [ "master" ]
# #   pull_request:
# #     branches: [ "master" ]
#
# #   # Allows you to run this workflow manually from the Actions tab
# #   workflow_dispatch:
#
# # # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# # jobs:
# #   # This workflow contains a single job called "build"
# #   build:
# #     # The type of runner that the job will run on
# #     runs-on: ubuntu-latest
#
# #     # Steps represent a sequence of tasks that will be executed as part of the job
# #     steps:
# #       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
# #       - uses: actions/checkout@v3
#
# #       # Runs a single command using the runners shell
# #       - name: Run a one-line script
# #         run: echo Hello, world!
#
# #       # Runs a set of commands using the runners shell
# #       - name: Run a multi-line script
# #         run: |
# #           echo Add other actions to build,
# #           echo test, and deploy your project.
#
